version: '3'
services:
  directus:
    container_name: directus
    image: directus/directus:latest
    restart: unless-stopped
    network_mode: "host"
    ports:
      - 8055:8055
    volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - ./uploads:/directus/uploads
      # Make sure to also mount the volume when using SQLite
      # - ./database:/directus/database
      # If you want to load extensions from the host
      # - ./extensions:/directus/extensions
    environment:
      KEY: 'akeyuuid'
      SECRET: 'akeyuuid'
      #LOG_LEVEL: 'trace'

      DB_CLIENT: 'mysql'
      DB_HOST: '0.0.0.0'
      DB_PORT: '3306'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'thepass'

      ADMIN_EMAIL: 'example@gmail.com'
      ADMIN_PASSWORD: 'thepass'

      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      PUBLIC_URL: 'https://cms.example.com'

      EMAIL_FROM: 'mailman@example.com'
      EMAIL_TRANSPORT: 'smtp'
      EMAIL_SMTP_HOST: 'mail.example.com'
      EMAIL_SMTP_PORT: '587'
      EMAIL_SMTP_USER: 'mailman@example.com'
      EMAIL_SMTP_PASSWORD: 'thepass'
      #EMAIL_SMTP_SECURE: 'true'
